clone_depth: 10

version: 5.2.{build}

test: off

branches:
  only:
    - win_build

skip_tags: true

build:
  parallel: true
  verbosity: detailed

platform:
  - x64
  # - x86

configuration:
  #- Debug
  - Release

environment:
  CMAKE_GENERATOR: Visual Studio 14 2015 Win64
  OPENVDB_ABI: 5
  VCPKG_DEFAULT_TRIPLET: x64-windows
  VCPKG_x64_SHARED_ROOT: C:/tools/vcpkg/installed/x64-windows

os:
  - Visual Studio 2015

cache: c:\tools\vcpkg\installed\
# cache: c:\tools\vcpkg\installed\ -> appveyor.yml

before_build:
  - cmd: cd C:\tools\vcpkg
  - cmd: vcpkg install glew glfw3 zlib blosc openexr tbb cppunit
  - cmd: vcpkg integrate install
  - cmd: set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;%VCPKG_x64_SHARED_ROOT%

  - cmd: set BOOST_ROOT=C:\Libraries\boost_1_67_0
  - cmd: set BOOST_LIBRARYDIR=C:\Libraries\boost_1_67_0\lib64-msvc-14.0
  - cmd: set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;%BOOST_ROOT%

  - cmd: set PYTHON_ROOT = "C:\Python27-x64"
  - cmd: set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;%PYTHON_ROOT%

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: mkdir build
  - cmd: cd build
    # Build to match Houdini 16.5 ABI (OpenVDB 4.0.1)
  - cmd: cmake .. -G"%CMAKE_GENERATOR%" -DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DOPENVDB_ABI_VERSION_NUMBER=%OPENVDB_ABI% -DUSE_GLFW3=ON -DOPENVDB_BUILD_PYTHON_MODULE=OFF -DOPENVDB_BUILD_UNITTESTS=OFF -DOPENVDB_BUILD_DOCS=OFF -DCPPUNIT_LOCATION=%VCPKG_x64_SHARED_ROOT% -DOPENEXR_LOCATION=%VCPKG_x64_SHARED_ROOT% -DILMBASE_LOCATION=%VCPKG_x64_SHARED_ROOT% -DTBB_LOCATION=%VCPKG_x64_SHARED_ROOT% -DBLOSC_LOCATION=%VCPKG_x64_SHARED_ROOT% -DGLEW_LOCATION=%VCPKG_x64_SHARED_ROOT% -DGLFW3_LOCATION=%VCPKG_x64_SHARED_ROOT% 
  - cmd: cmake --build . --config %CONFIGURATION% --target install

#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#on_failure:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


